### ISSUE TITLE
Docker 2.2.0.0 Windows can't connect to Containers

### ISSUE THREAD

**Issue by mduwe-abd** [drud/ddev#2044]
Setup:
Windows: 1909
Docker: 2.2.0.0 (stable)
ddev: 1.12.2

Can't run `ddev ssh` 
Traceback (most recent call last):
  File "docker-compose", line 6, in <module>
  File "compose\cli\main.py", line 72, in main
  File "compose\cli\main.py", line 128, in perform_command
  File "compose\cli\main.py", line 491, in exec_command
  File "compose\cli\main.py", line 1469, in call_docker
  File "subprocess.py", line 172, in call
  File "subprocess.py", line 394, in __init__
  File "subprocess.py", line 644, in _execute_child
TypeError: environment can only contain strings
[23240] Failed to execute script docker-compose

Docker was updated to 2.2.0.0
The post-start hook failed with same error, while debugging the hook command

`docker-compose -f {PATH_TO_DDEV_PROJECT}\.ddev\docker-compose.yaml exec -w /var/www/html/ -T web bash -c a2enmod headersdocker-compose [-f  {PATH_TO_DDEV_PROJECT}\.ddev\docker-compose.yaml exec -w /var/www/html/ -T web bash -c a2enmod headers`

docker message:
ERROR: No container found for web_1

ddev_config:
APIVersion: v1.12.2
name: website
type: typo3
docroot: web
php_version: "7.2"
webserver_type: apache-fpm
router_http_port: "80"
router_https_port: "443"
xdebug_enabled: false
additional_hostnames: []
additional_fqdns:
- website.ddev.local
mariadb_version: "10.2"
nfs_mount_enabled: false
provider: default
hooks:
  post-start:
  - exec: a2enmod headers
use_dns_when_possible: true
timezone: ""

**Comment by mduwe-abd** [comment]
Duplicate to https://github.com/drud/ddev/issues/2043
