### ISSUE TITLE
Cannot start on Windows 10 (docker-compose python stack trace)

### ISSUE THREAD

**Issue by jepster** [drud/ddev#2140]
**Describe the bug**
I am using Windows 10 Professional with 64 bit. I have Docker in version 19.03.8. I am using the Powershell. I have installed DDEV with Chocholatey. Like recommended in the installation instruction. If I execute the "ddev start" command for my Drupal 8 project, the following error occurs:
```
PS C:\Users\Peter\dev\degov> ddev start
Not loading custom commands; bash is not in PATH
Unable to find bash.exe in PATH, not loading custom commands
Starting degov...
Building ddev-ssh-agent
[11040] Failed to execute script docker-compose
Traceback (most recent call last):
  File "site-packages\docker\credentials\store.py", line 80, in _execute
  File "subprocess.py", line 395, in check_output
  File "subprocess.py", line 487, in run
subprocess.CalledProcessError: Command '['C:\\Program Files\\Docker\\Docker\\resources\\bin\\docker-credential-desktop.EXE', 'list']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "docker-compose", line 6, in <module>
  File "compose\cli\main.py", line 72, in main
  File "compose\cli\main.py", line 128, in perform_command
  File "compose\cli\main.py", line 1077, in up
  File "compose\cli\main.py", line 1073, in up
  File "compose\project.py", line 548, in up
  File "compose\service.py", line 351, in ensure_image_exists
  File "compose\service.py", line 1106, in build
  File "site-packages\docker\api\build.py", line 261, in build
  File "site-packages\docker\api\build.py", line 308, in _set_auth_headers
  File "site-packages\docker\auth.py", line 302, in get_all_credentials
  File "site-packages\docker\credentials\store.py", line 71, in list
  File "site-packages\docker\credentials\store.py", line 93, in _execute
docker.credentials.errors.StoreError: Credentials store docker-credential-desktop exited with "error listing credentials - err: exit status 1, out: `Element nicht gefunden.`".
Failed to start degov: failed to start ddev-ssh-agent: Failed to run docker-compose [-f C:\Users\Peter/.ddev/ssh-auth-compose.yaml -p ddev-ssh-agent up --build --force-recreate -d], err='exit status 4294967295', stdout='', stderr='Building ddev-ssh-agent
[11040] Failed to execute script docker-compose
Traceback (most recent call last):
  File "site-packages\docker\credentials\store.py", line 80, in _execute
  File "subprocess.py", line 395, in check_output
  File "subprocess.py", line 487, in run
subprocess.CalledProcessError: Command '['C:\\Program Files\\Docker\\Docker\\resources\\bin\\docker-credential-desktop.EXE', 'list']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "docker-compose", line 6, in <module>
  File "compose\cli\main.py", line 72, in main
  File "compose\cli\main.py", line 128, in perform_command
  File "compose\cli\main.py", line 1077, in up
  File "compose\cli\main.py", line 1073, in up
  File "compose\project.py", line 548, in up
  File "compose\service.py", line 351, in ensure_image_exists
  File "compose\service.py", line 1106, in build
  File "site-packages\docker\api\build.py", line 261, in build
  File "site-packages\docker\api\build.py", line 308, in _set_auth_headers
  File "site-packages\docker\auth.py", line 302, in get_all_credentials
  File "site-packages\docker\credentials\store.py", line 71, in list
  File "site-packages\docker\credentials\store.py", line 93, in _execute
docker.credentials.errors.StoreError: Credentials store docker-credential-desktop exited with "error listing credentials - err: exit status 1, out: `Element nicht gefunden.`".'
PS C:\Users\Peter\dev\degov>
```

**To Reproduce**
1. Run ddev start
2. Select "drupal8"

**Expected behavior**
The project should be created correctly. I should be able to run a stack with running Drupal.

**Version and configuration information (please complete the following information):**
 - Windows 10 Professional
 -  Docker in version 19.03.8
 - ddev version: 1.13.1
 - config.yaml contents for the misbehaving project:
```
APIVersion: v1.13.1
name: degov
type: drupal8
docroot: ""
php_version: "7.3"
webserver_type: nginx-fpm
router_http_port: "80"
router_https_port: "443"
xdebug_enabled: false
additional_hostnames: []
additional_fqdns: []
nfs_mount_enabled: false
provider: default
use_dns_when_possible: true
timezone: ""


# This config.yaml was created with ddev version v1.13.1
# webimage: drud/ddev-webserver:v1.13.1
# dbimage: drud/ddev-dbserver-mariadb-10.2:v1.13.0
# dbaimage: phpmyadmin/phpmyadmin:5
# However we do not recommend explicitly wiring these images into the
# config.yaml as they may break future versions of ddev.
# You can update this config.yaml using 'ddev config'.

# Key features of ddev's config.yaml:

# name: <projectname> # Name of the project, automatically provides
#   http://projectname.ddev.site and https://projectname.ddev.site

# type: <projecttype>  # drupal6/7/8, backdrop, typo3, wordpress, php

# docroot: <relative_path> # Relative path to the directory containing index.php.

# php_version: "7.3"  # PHP version to use, "5.6", "7.0", "7.1", "7.2", "7.3", "7.4"

# You can explicitly specify the webimage, dbimage, dbaimage lines but this
# is not recommended, as the images are often closely tied to ddev's' behavior,
# so this can break upgrades.

# webimage: <docker_image>  # nginx/php docker image.
# dbimage: <docker_image>  # mariadb docker image.
# dbaimage: <docker_image>

# mariadb_version and mysql_version
# ddev can use many versions of mariadb and mysql
# However these directives are mutually exclusive
# mariadb_version: 10.2
# mysql_version: 8.0

# router_http_port: <port>  # Port to be used for http (defaults to port 80)
# router_https_port: <port> # Port for https (defaults to 443)

# xdebug_enabled: false  # Set to true to enable xdebug and "ddev start" or "ddev restart"
# Note that for most people the commands
# "ddev exec enable_xdebug" and "ddev exec disable_xdebug" work better,
# as leaving xdebug enabled all the time is a big performance hit.

# webserver_type: nginx-fpm  # Can be set to apache-fpm or apache-cgi as well

# timezone: Europe/Berlin
# This is the timezone used in the containers and by PHP;
# it can be set to any valid timezone,
# see https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
# For example Europe/Dublin or MST7MDT

# additional_hostnames:
#  - somename
#  - someothername
# would provide http and https URLs for "somename.ddev.site"
# and "someothername.ddev.site".

# additional_fqdns:
#  - example.com
#  - sub1.example.com
# would provide http and https URLs for "example.com" and "sub1.example.com"
# Please take care with this because it can cause great confusion.

# upload_dir: custom/upload/dir
# would set the destination path for ddev import-files to custom/upload/dir.

# working_dir:
#   web: /var/www/html
#   db: /home
# would set the default working directory for the web and db services.
# These values specify the destination directory for ddev ssh and the
# directory in which commands passed into ddev exec are run.

# omit_containers: ["dba", "ddev-ssh-agent"]
# would omit the dba (phpMyAdmin) and ddev-ssh-agent containers. Currently
# only those two containers can be omitted here.
# Note that these containers can also be omitted globally in the
# ~/.ddev/global_config.yaml or with the "ddev config global" command.

# nfs_mount_enabled: false
# Great performance improvement but requires host configuration first.
# See https://ddev.readthedocs.io/en/stable/users/performance/#using-nfs-to-mount-the-project-into-the-container

# host_https_port: "59002"
# The host port binding for https can be explicitly specified. It is
# dynamic unless otherwise specified.
# This is not used by most people, most people use the *router* instead
# of the localhost port.

# host_webserver_port: "59001"
# The host port binding for the ddev-webserver can be explicitly specified. It is
# dynamic unless otherwise specified.
# This is not used by most people, most people use the *router* instead
# of the localhost port.

# host_db_port: "59002"
# The host port binding for the ddev-dbserver can be explicitly specified. It is dynamic
# unless explicitly specified.

# phpmyadmin_port: "1000"
# The PHPMyAdmin port can be changed from the default 8036

# mailhog_port: "1001"
# The MailHog port can be changed from the default 8025

# webimage_extra_packages: [php-yaml, php7.3-ldap]
# Extra Debian packages that are needed in the webimage can be added here

# dbimage_extra_packages: [telnet,netcat]
# Extra Debian packages that are needed in the dbimage can be added here

# use_dns_when_possible: true
# If the host has internet access and the domain configured can
# successfully be looked up, DNS will be used for hostname resolution
# instead of editing /etc/hosts
# Defaults to true

# project_tld: ddev.site
# The top-level domain used for project URLs
# The default "ddev.site" allows DNS lookup via a wildcard
# If you prefer you can change this to "ddev.local" to preserve
# pre-v1.9 behavior.

# ngrok_args: --subdomain mysite --auth username:pass
# Provide extra flags to the "ngrok http" command, see
# https://ngrok.com/docs#http or run "ngrok http -h"

# disable_settings_management: false
# If true, ddev will not create CMS-specific settings files like
# Drupal's settings.php/settings.ddev.php or TYPO3's AdditionalSettings.php
# In this case the user must provide all such settings.

# provider: default # Currently either "default" or "pantheon"
#
# Many ddev commands can be extended to run tasks before or after the
# ddev command is executed, for example "post-start", "post-import-db",
# "pre-composer", "post-composer"
# See https://ddev.readthedocs.io/en/stable/users/extending-commands/ for more
# information on the commands that can be extended and the tasks you can define
# for them. Example:
#hooks:
# post-import-db:
#   - exec: drush cr
#   - exec: drush updb

```
 - Do you have any custom configuration (nginx, php, mysql) in the .ddev folder? If so, have you tried without them?

No, I have no custom configuration.

**Additional context**

I have already tried to set the latest Docker Compose version, since I stumbled over the following issue here: https://github.com/drud/ddev/issues/2043. The described workaround was not working for me. I have also not set any ".env" file.

**Comment by rfay** [comment]
It looks like you have a bad docker-compose; Please

* Use git-bash for executions of ddev, it's the most likely to succeed
* Please give the result of `docker-compose --version`
* Please let me know the result of `which docker-compose`
* Please provide the version of Docker Desktop for Windows that you're using (In the "whale" menu, about). 

If you have ever had any version of Docker Toolbox installed, please remove all traces of it, including ~/.docker

Thanks!

**Comment by rfay** [comment]
It looks like you probably have https://github.com/docker/compose/issues/7273

**Comment by rfay** [comment]
I'm pretty sure that if you uninstall docker (all versions) `rm -r ~/.docker` and reinstall docker desktop for Windows, you'll solve this, judging from the various things I find in https://www.google.com/search?q=docker-compose+File+%22site-packages%5Cdocker%5Ccredentials%5Cstore.py%22%2C+line+80%2C+in+_execute&oq=docker-compose+File+%22site-packages%5Cdocker%5Ccredentials%5Cstore.py%22%2C+line+80%2C+in+_execute&aqs=chrome..69i57.1847j0j7&sourceid=chrome&ie=UTF-8

**Comment by jepster** [comment]
> I'm pretty sure that if you uninstall docker (all versions) rm -r ~/.docker and reinstall docker desktop for Windows, you'll solve this

I have installed Windows 10 Professional from scratch, just to try ddev on windows. :) Are you really sure, that I need to install docker twice?

**Comment by rfay** [comment]
I'm pretty sure the version of docker-compose that you have is *not* the one that is shipped with Docker Desktop for Windows.  My suggestions in https://github.com/drud/ddev/issues/2140#issuecomment-606219013 and https://github.com/drud/ddev/issues/2140#issuecomment-606221731 are all I have for starters.  If you find another path, I know you'll report it here.
