### ISSUE TITLE
panic in `ddev describe` in  1.18.0-rc1  with mutagen enabled globally

### ISSUE THREAD

**Issue by marcoscano** [drud/ddev#3210]
**Run a Diagnostic and Paste Link Here**

https://gist.github.com/marcoscano/60bb920bd10674a9166a86b1254df1a9

**Describe the bug**

Just upgraded from alpha4 into rc1:

```
$ ddev poweroff
$ brew upgrade drud/ddev-edge/ddev
...
==> Upgrading 1 outdated package:
drud/ddev-edge/ddev 1.18.0-alpha4 -> 1.18.0-rc1
==> Upgrading drud/ddev-edge/ddev
  1.18.0-alpha4 -> 1.18.0-rc1 
... 
```

Then `ddev start` and `ddev restart` work fine.

However, when I try `ddev describe` I get:

```
$ ddev describe
tWidth=279 urlPortWidth=111.6 infoWidth=69 
panic: interface conversion: interface {} is nil, not string

goroutine 1 [running]:
github.com/drud/ddev/cmd/ddev/cmd.renderAppDescribe(0xc000438300, 0xc000110000, 0xc000110000, 0x0, 0x0, 0x1)
	/workdir/cmd/ddev/cmd/describe.go:143 +0x27df
github.com/drud/ddev/cmd/ddev/cmd.glob..func14(0x1ab93a0, 0x1af7680, 0x0, 0x0)
	/workdir/cmd/ddev/cmd/describe.go:52 +0x185
github.com/spf13/cobra.(*Command).execute(0x1ab93a0, 0x1af7680, 0x0, 0x0, 0x1ab93a0, 0x1af7680)
	/workdir/vendor/github.com/spf13/cobra/command.go:854 +0x2c2
github.com/spf13/cobra.(*Command).ExecuteC(0x1abcac0, 0x1f5, 0x0, 0x0)
	/workdir/vendor/github.com/spf13/cobra/command.go:958 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
	/workdir/vendor/github.com/spf13/cobra/command.go:895
github.com/drud/ddev/cmd/ddev/cmd.Execute()
	/workdir/cmd/ddev/cmd/root.go:151 +0x3c
main.main()
	/workdir/cmd/ddev/main.go:21 +0xd9
```

**To Reproduce**

**Expected behavior**

**Screenshots**

**Version and configuration information (please complete the following information):**

- Host computer OS and Version: macOS BigSur 11.5.2
- Docker Desktop version if on macOS or Windows: 3.6.0
- ddev version information (use `ddev version`)

```
$ ddev version
 ITEM            VALUE                                                            
 DDEV version    v1.18.0-rc1                                                      
 architecture    amd64                                                            
 db              drud/ddev-dbserver-mariadb-10.3:20210729_cspitzlay_mysql_history 
 dba             phpmyadmin:5                                                     
 ddev-ssh-agent  drud/ddev-ssh-agent:v1.17.0                                      
 docker          20.10.8                                                          
 docker-compose  1.29.2                                                           
 mutagen         0.12.0-beta5                                                     
 os              darwin                                                           
 router          drud/ddev-router:v1.17.6                                         
 web             drud/ddev-webserver:20210823_bump_upstream_webserver 
```

- config.yaml contents for the misbehaving project (the part before the comments)

```
name: foobar
type: drupal9
docroot: web
php_version: "7.4"
webserver_type: nginx-fpm
router_http_port: "9080"
router_https_port: "9443"
xdebug_enabled: false
additional_hostnames: []
additional_fqdns: []
mariadb_version: "10.4"
mysql_version: ""
nfs_mount_enabled: false
mutagen_enabled: false
use_dns_when_possible: true
disable_settings_management: true
timezone: "America/Los_Angeles"
composer_version: "2"
web_environment: []
```

- Do you have any custom configuration (nginx, php, mysql) in the .ddev folder? If so, have you tried without them?

The only thing I can see is php with 
```
[PHP]
memory_limit = -1;
```

**Additional context**

I have mutagen enabled globally, not on a per-project basis.

**Comment by marcoscano** [comment]
Note: I'm realizing now that I don't remember executing `ddev describe` in -alpha4, which I upgraded to a few days ago. So I'm not 100% sure this worked in alpha4 either.

**Comment by rfay** [comment]
Thanks for the great report. This should be enough to solve it. 

It appears to be the code in https://github.com/drud/ddev/blob/bc2bf2b108ddb250a257773e75c1e9fd10c5479e/cmd/ddev/cmd/describe.go#L143-L142 - I assume it's about mutagen being enabled globally, I've been testing per-project.

There was massive PR on `ddev describe` that was the last thing into rc1.
