### ISSUE TITLE
Nightly build broken on solr service addition

### ISSUE THREAD

**Issue by rfay** [drud/ddev#365]
## What happened (or feature request):

The nightly build broke last night, presumably a result of #344 being committed. My bet is that we just need to add the related container to the submodule container builds, etc.

I think we probably will want to start triggering the nightly build manually on significant PRs before committing them. 

Note that there may be two separate problems here: 
1. The failure to find the container.
2. The resultant panic shouldn't have happened, and should be looked at.

```
--- FAIL: TestServices (5.38s)
	Error Trace:	servicetest_test.go:79
	Error:		Received unexpected error exit status 1
		

	Error Trace:	servicetest_test.go:92
	Error:		Received unexpected error could not find containers which matched search criteria: map[com.ddev.site-name:TestServicesDrupal8 com.docker.compose.service:solr]
		

panic: runtime error: index out of range [recovered]
	panic: runtime error: index out of range

goroutine 7 [running]:
testing.tRunner.func1(0xc42005fc70)
	/usr/local/go/src/testing/testing.go:622 +0x29d
panic(0x861d40, 0xb09c10)
	/usr/local/go/src/runtime/panic.go:489 +0x2cf
github.com/drud/ddev/pkg/servicetest_test.TestServices(0xc42005fc70)
	/home/circleci/go/src/github.com/drud/ddev/pkg/servicetest/servicetest_test.go:93 +0x1119
testing.tRunner(0xc42005fc70, 0x8fe7a0)
	/usr/local/go/src/testing/testing.go:657 +0x96
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:697 +0x2ca
FAIL	github.com/drud/ddev/pkg/servicetest	5.387s
```

## Related source links or issues:

**Comment by beeradb** [comment]
This was fixed in #368
