### ISSUE TITLE
`ddev get drud/ddev-platformsh` fails with panic 

### ISSUE THREAD

**Issue by rfay** [drud/ddev#4579]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Expected Behavior

`ddev get drud/ddev-platformsh` shouldn't panic

### Actual Behavior

Panic.

### Steps To Reproduce

```
$ ddev get drud/ddev-platformsh
Downloading https://api.github.com/repos/drud/ddev-platformsh/tarball/v0.6.4
v0.6.4_4272473176.tar.gz 99.83 KiB / 99.83 KiB [====================================] 100.00% 0s
panic: interface conversion: interface {} is bool, not string

goroutine 1 [running]:
github.com/drud/ddev/pkg/util.YamlToDict({0x102bf3680?, 0x140001f7560?})
	/Users/rfay/workspace/ddev/pkg/util/yamltools.go:33 +0x510
github.com/drud/ddev/pkg/util.YamlToDict({0x102bf3680?, 0x140001f74d0?})
	/Users/rfay/workspace/ddev/pkg/util/yamltools.go:38 +0x39c
github.com/drud/ddev/pkg/util.YamlToDict({0x102bf5420?, 0x140001f7260?})
	/Users/rfay/workspace/ddev/pkg/util/yamltools.go:58 +0x6d4
github.com/drud/ddev/pkg/util.YamlToDict({0x102bf5420?, 0x140001f71d0?})
	/Users/rfay/workspace/ddev/pkg/util/yamltools.go:60 +0x61c
github.com/drud/ddev/cmd/ddev/cmd.glob..func29(0x103035a00?, {0x140000ac900?, 0x1, 0x1})
	/Users/rfay/workspace/ddev/cmd/ddev/cmd/get.go:190 +0xe48
github.com/spf13/cobra.(*Command).execute(0x103035a00, {0x140000ac8d0, 0x1, 0x1})
	/Users/rfay/workspace/ddev/vendor/github.com/spf13/cobra/command.go:860 +0x4ac
github.com/spf13/cobra.(*Command).ExecuteC(0x103039100)
	/Users/rfay/workspace/ddev/vendor/github.com/spf13/cobra/command.go:974 +0x354
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/rfay/workspace/ddev/vendor/github.com/spf13/cobra/command.go:902
github.com/drud/ddev/cmd/ddev/cmd.Execute()
	/Users/rfay/workspace/ddev/cmd/ddev/cmd/root.go:143 +0x40
main.main()
	/Users/rfay/workspace/ddev/cmd/ddev/main.go:20 +0xac
```

### Anything else?

This happens when the following is in .platform.app.yaml:

```yaml
    nodejs:
      # Install node version manager
      # See https://www.npmjs.com/package/n
      n: "*"
```

**Comment by rfay** [comment]
DDEV is trying to parse the line `n: "*"` and that fails; the single-character key comes out to be `false`, which can't be converted to a string.  Just changing that to 

```
    nodejs:
      nx: '*'
```

makes everything work fine. 

I'm not sure whether this is a bug in the yaml parser or something DDEV's doing that's odd. A single-character key is unusual, but I don't see why it would fail.

**Comment by rfay** [comment]
The original yaml.Unmarshall() is getting this:
https://github.com/drud/ddev/blob/16c3aa2a5f1aa198964bd5ce053a5c5773181efb/pkg/util/yamltools.go#L18

<img width="455" alt="image" src="https://user-images.githubusercontent.com/112444/214444487-33b7fd52-7082-4e67-a994-dcf89046caa9.png">

**Comment by rfay** [comment]
Weirder still, I can use `a: "*"` or `b: "*"` or `z: "*"` without trouble.
